=== wuwenshan/MLBDA/dtd/restaurant.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT restaurant (nom, lieu,  etoile, fermeture, menu+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT fermeture (#PCDATA)>
<!ELEMENT etoile (#PCDATA)>
<!ELEMENT lieu EMPTY>
<!ATTLIST lieu nom CDATA #REQUIRED departement CDATA #REQUIRED plusBeauMonument CDATA #REQUIRED>
<!ELEMENT menu (nom,prix)>
<!ELEMENT prix (#PCDATA)>

=== wuwenshan/MLBDA/dtd/restaurant.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">


<restaurant>
  <nom>Restaurant Universitaire</nom>
  <lieu nom="Paris" departement="75" plusBeauMonument="Louvre" />
  <etoile>0</etoile>
  <fermeture>we</fermeture>
  <menu>
    <nom>Unique</nom>
    <prix>2Euros</prix>
  </menu>
</restaurant>
